### ISSUE TITLE
PermissionsResult should contain the name of the permission

### ISSUE THREAD

**Issue by faifai21** [ralphpina/Android-Permissions-Manager#3]
This is especially helpful when requesting multiple permissions at a time. PermissionsResult is more useful if you request one permission. If you request more than one permission, PermissionsResult won't get give you any info as to what permission was rejected and which was granted.

On that same topic, when requesting multiple permissions, a list of permission results should be returned, and not just a single one.

**Comment by ralphpina** [comment]
Re-wrote the API. In the newest version, 3.0.0 the `PermissionsResult` class has the `Permission` requested. The `Permission.value` property is the Android String constant for the permission, for example `android.permission.CAMERA`.
