### ISSUE TITLE
requestStoragePermission does  not work .

### ISSUE THREAD

**Issue by huanjulu** [ralphpina/Android-Permissions-Manager#6]
PermissionsManager.get()
                        .requestStoragePermission()
                        .subscribe(new Action1<PermissionsResult>() {
                            @Override
                            public void call(PermissionsResult permissionsResult) {
                                if (permissionsResult.isGranted()) {

                                    initResumeUi();

                                } else {

                                    ReceiptActivity.this
                                            .finish();
                                }
                            }
                        });

**Comment by TianDaGe** [comment]
same here

**Comment by TianDaGe** [comment]
And I think, it should need multi permission management feature.

**Comment by ralphpina** [comment]
@huanjulu I have not done a good job maintaining this library. However, I just re-wrote with a new API. You can now request Storage in a more granular fashion using `Permission.Storage.WriteExternal` and `Permission.Storage.ReadExternal` that map to `android.permission.READ_EXTERNAL_STORAGE` and `android.permission.WRITE_EXTERNAL_STORAGE`. 

If it's still broken in the new version, I will fix it.
