### ISSUE TITLE
Rename function

### ISSUE THREAD

**Issue by davidantoon** [ralphpina/Android-Permissions-Manager#7]
## Fix the README.md file

*Replace this: *
`PermissionsManager.get()
                  .isAudioRecordingGranted()
PermissionsManager.get()
                  .hasAskedForAudioRecordingPermission()
PermissionsManager.get()
                  .neverAskForAudio(mActivity);`
*With: *
`PermissionsManager.get()
                  .isMicrophoneGranted()
PermissionsManager.get()
                  .hasAskedForMicrophonePermission()
PermissionsManager.get()
                  .neverAskForMicrophone(mActivity);`

**Comment by ralphpina** [comment]
@davidantoon thanks for the suggestion. Sorry for being slow to reply, I haven't done a good job of maintaining this library. I just published a new version with an updated API. It will allow you to ask for permissions in a more granular fashion. The old implementation requested everything in a group.
