### ISSUE TITLE
Requesting multiple permissions example code doesn't exist

### ISSUE THREAD

**Issue by itaispector** [ralphpina/Android-Permissions-Manager#8]
Trying to use this code snippet, but using `requestPermissions`, then callin `subscribe` isn't available.

```
PermissionsManager.get()
      .requestPermissions(REQUEST_CAMERA_PERMISSION, REQUEST_LOCATION_PERMISSION)
      .subscribe(new Action1<PermissionsResult>() {
          @Override
          public void call(PermissionsResult permissionsResult) {
            if (permissionsResult.isGranted()) { // always true pre-M
              // do whatever
            }
            if (permissionsResult.hasAskedForPermissions()) { // false if pre-M
              // do whatever
            }
          }
      });
```

I get this following message:
```
Cannot access ‘subscribe(rx.functions.Action1<? super net.ralphpina.permissionsmanager.PermissionsResult>)’ in ‘rx.Observable’
```

*update:*
I forked the repo, and added `public` access modifier to `PermissionsObservable`, and now `subscribe` function is available
Should I PR?

**Comment by webnizam** [comment]
@itaispector can you please share the fix you did to fix this "Cannot access ‘subscribe(rx.functions.Action1<? super net.ralphpina.permissionsmanager.PermissionsResult>)’ in ‘rx.Observable’" issue?

**Comment by itaispector** [comment]
@webnizam sure, check this out:
https://github.com/itaispector/Android-Permissions-Manager/commit/b101f5e7f75bfe200d509497bfa89a420f5abce0

All i did was changing this class encapsulation to public

**Comment by ralphpina** [comment]
@itaispector thanks for reporting this. I haven't done a good job of maintaining the library. But I have updated it with a new API. Let me know if you still see the issue.
